# Generated by Django 3.2.3 on 2021-10-09 12:46

import api.models.post_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.post_model.post_name),
        ),
    ]
