# Generated by Django 3.2.3 on 2021-10-09 17:34

import api.models.comment_model
import api.models.post_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211009_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.comment_model.generated_name),
        ),
        migrations.AddField(
            model_name='post',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.post_model.generated_name),
        ),
    ]
